 plaintexts = [
            "London calling to the faraway towns",
            "Now war is declared and battle come down",
            "London calling just to the underworld",
            "Come out of the cupboard, you boys and girls",
            "London calling, now don't look to us",
            "Phony Beatlemania has bitten the dust",
            "London calling, see we ain't got no swing",
            "'Cept for the ring of that truncheon thing",
            "The ice age is coming, the sun is zooming in",
            "Meltdown expected, the wheat is growin' thin",
            "Engines stop running, but I have no fear",
            "Cause London is drowning, and I, I live by the river",
            "London calling to the imitation zone",
            "Forget it, brother, you can go it alone",
            "London calling to the zombies of death",
            "Quit holding out and draw another breath",
            "London calling and I don't want to shout",
            "But when we were talking I saw you nodding out",
            "London calling, see we ain't got no high",
            "Except for that one with the yellowy eye",
            "Now get this",
            "London calling, yes, I was there, too",
            "An' you know what they said? Well, some of it was true!",
            "London calling at the top of the dial",
            "And after all this, won't you give me a smile?",
            "I never felt so much a' like a'like a'like",
            "When they kick at your front door",
            "How you gonna come?",
            "With your hands on your head",
            "Or on the trigger of your gun",
            "When the law break in",
            "How you gonna go?",
            "Shot down on the pavement",
            "Or waiting on death row",
            "You can crush us",
            "You can bruise us",
            "But you'll have to answer to",
            "Oh, the guns of Brixton",
            "The money feels good",
            "And your life you like it well",
            "But surely your time will come",
            "As in heaven, as in hell",
            "You see, he feels like Ivan",
            "Born under the Brixton sun",
            "His game is called survivin'",
            "At the end of the harder they come",
            "You know it means no mercy",
            "They caught him with a gun",
            "No need for the Black Maria",
            "Goodbye to the Brixton sun",
            "You can crush us",
            "You can bruise us",
            "Yes, even shoot us",
            "But oh-the guns of Brixton",
            "Shot down on the pavement",
            "Waiting in death row",
            "His game is called survivin'",
            "As in heaven as in hell",
            "Anybody who makes speeches written ",
            "by someone else is just a robot."]

        ciphertexts = [
            "Svukvu jhsspun av aol mhyhdhf avduz",
            "Uvd dhy pz kljshylk huk ihaasl jvtl kvdu",
            "Svukvu jhsspun qbza av aol buklydvysk",
            "Jvtl vba vm aol jbwivhyk, fvb ivfz huk npysz",
            "Svukvu jhsspun, uvd kvu'a svvr av bz",
            "Wovuf Ilhaslthuph ohz ipaalu aol kbza",
            "Svukvu jhsspun, zll dl hpu'a nva uv zdpun",
            "'Jlwa mvy aol ypun vm aoha aybujolvu aopun",
            "Aol pjl hnl pz jvtpun, aol zbu pz gvvtpun pu",
            "Tlsakvdu lewljalk, aol dolha pz nyvdpu' aopu",
            "Lunpulz zavw ybuupun, iba P ohcl uv mlhy",
            "Jhbzl Svukvu pz kyvdupun, huk P, P spcl if aol ypcly",
            "Svukvu jhsspun av aol ptpahapvu gvul",
            "Mvynla pa, iyvaoly, fvb jhu nv pa hsvul",
            "Svukvu jhsspun av aol gvtiplz vm klhao",
            "Xbpa ovskpun vba huk kyhd huvaoly iylhao",
            "Svukvu jhsspun huk P kvu'a dhua av zovba",
            "Iba dolu dl dlyl ahsrpun P zhd fvb uvkkpun vba",
            "Svukvu jhsspun, zll dl hpu'a nva uv opno",
            "Lejlwa mvy aoha vul dpao aol flssvdf lfl",
            "Uvd nla aopz",
            "Svukvu jhsspun, flz, P dhz aolyl, avv",
            "Hu' fvb ruvd doha aolf zhpk? Dlss, zvtl vm pa dhz aybl!",
            "Svukvu jhsspun ha aol avw vm aol kphs",
            "Huk hmaly hss aopz, dvu'a fvb npcl tl h ztpsl?",
            "P ulcly mlsa zv tbjo h' sprl h'sprl h'sprl",
            "Dolu aolf rpjr ha fvby myvua kvvy",
            "Ovd fvb nvuuh jvtl?",
            "Dpao fvby ohukz vu fvby olhk",
            "Vy vu aol aypnnly vm fvby nbu",
            "Dolu aol shd iylhr pu",
            "Ovd fvb nvuuh nv?",
            "Zova kvdu vu aol whcltlua",
            "Vy dhpapun vu klhao yvd",
            "Fvb jhu jybzo bz",
            "Fvb jhu iybpzl bz",
            "Iba fvb'ss ohcl av huzdly av",
            "Vo, aol nbuz vm Iypeavu",
            "Aol tvulf mllsz nvvk",
            "Huk fvby spml fvb sprl pa dlss",
            "Iba zbylsf fvby aptl dpss jvtl",
            "Hz pu olhclu, hz pu olss",
            "Fvb zll, ol mllsz sprl Pchu",
            "Ivyu bukly aol Iypeavu zbu",
            "Opz nhtl pz jhsslk zbycpcpu'",
            "Ha aol luk vm aol ohykly aolf jvtl",
            "Fvb ruvd pa tlhuz uv tlyjf",
            "Aolf jhbnoa opt dpao h nbu",
            "Uv ullk mvy aol Ishjr Thyph",
            "Nvvkifl av aol Iypeavu zbu",
            "Fvb jhu jybzo bz",
            "Fvb jhu iybpzl bz",
            "Flz, lclu zovva bz",
            "Iba vo-aol nbuz vm Iypeavu",
            "Zova kvdu vu aol whcltlua",
            "Dhpapun pu klhao yvd",
            "Opz nhtl pz jhsslk zbycpcpu'",
            "Hz pu olhclu hz pu olss",
            "Hufivkf dov thrlz zwlljolz dypaalu ",
            "if zvtlvul lszl pz qbza h yviva."]
